### ISSUE TITLE
Cards not displaying content on Android

### ISSUE THREAD

**Issue by SoManyIssues** [RisingOrange/anki-enhanced-cloze#21]
Even with full sync the cards won't display any content on Ankidroid. There is only the structure of the cards and the deck information but none of the actual content or clozes. when there is no cloze in a card, there is the message to please make one, even though according to the documentation it should be possible to have cards without clozes. What is this about and is there anything I can do?

Android 11
Anki 2.1.49
Ankidroid 2.15.6

**Comment by Fun-Ken** [comment]
I have the same issue. After the update all the Enhanced Cloze cards are broken. I get this on Android:

![photo_2022-02-04_19-47-06](https://user-images.githubusercontent.com/80119847/152585659-95fe6baf-f05b-4bd2-a225-9a04d3e836f3.jpg)

**Comment by RisingOrange** [comment]
I am working on it. If you need the cards on AnkiDroid right now you can download an earlier version of the add-on here: https://github.com/RisingOrange/anki-enhanced-cloze/releases/tag/1.1.4 and then in Anki Desktop go to the Edit menu in the browser and click "Update Enhanced Clozes v2" (to generate the contents of the Cloze1-99 fields and the data field).
There probably will be another update today that makes the cards work on AnkiDroid.
Sorry for the inconvenience caused by this.

**Comment by RisingOrange** [comment]
There's a new update to the add-on on AnkiWeb that fixes this problem. 

After installing the update please restart Anki. Then the message about the update will appear again and you can then click Ok. Then from the main Anki window go to Preferences -> Network -> Check "On next sync force changes in one direction"
Synchronize the local collection to AnkiWeb and then download it from there in AnkiDroid.

**Comment by RisingOrange** [comment]
@SoManyIssues creating notes without clozes only works on Anki Desktop not on mobile, I now added this to the description.
Did Anki warn you about missing clozes in AnkiDroid or in Anki Desktop?

**Comment by SoManyIssues** [comment]
in android. desktop was working fine

**Comment by RisingOrange** [comment]
Ok, I'm glad

**Comment by SoManyIssues** [comment]
wow fastest support in all of github. Thank you very much for fixing and for this awesome plugin.
