### ISSUE TITLE
Strange jumping front to back

### ISSUE THREAD

**Issue by sfelix1** [RisingOrange/anki-enhanced-cloze#34]
There is a strange glitch when I hit answer, the devider and extra information seems to jump up. Does anyone have a fix?

Video:
https://user-images.githubusercontent.com/44973280/170110760-853e1794-16c6-4405-8f96-b1c661cf4ce2.mov

Setup:
macOS Monterey 12.0.1
Anki 2.52 (same problem with earlier versions. Edit: 2.40 works fine, what could cause the issue?)

Thanks in advance!

**Comment by RisingOrange** [comment]
Sorry for the late reply, you can turn off this behaviour by setting the "scrollToClozeOnToggle" option from true to false in the template of the note type.

https://raw.githubusercontent.com/RisingOrange/anki-enhanced-cloze/master/screenshots/configuration.png

You can reach this window this way:
Tools -> Manage note types -> Enhanced Cloze 2.1 v2 -> Cards

**Comment by sfelix1** [comment]
Thanks and no problem!

I tried that already, doesn't work unfortunately. I also tried to modify other parameters of the script, but didn't find a fix.

**Comment by RisingOrange** [comment]
I understand what you mean now. This jumping happens because the note type has some code in it that has to process the text and generate the enhanced clozes. The processing doesn't happen instantly and that's why it looks like that. I don't think that here is much I can do to stop it. 

What you can do (if it bothers you) is to remove the horizontal bar from the note type because it seems to me that the jumping is the most noticeable when you look at the bar. To remove the bar you have to delete `<hr>` from this place in the card template of the note type:

<img width="959" alt="EnhancedCloze_horizontal_bar" src="https://user-images.githubusercontent.com/31575114/179422966-ba464229-be48-46d9-97ef-75829ec3b739.png">
